workerPoolSpecs:
  machineSpec:
    machineType: n1-standard-4
  replicaCount: 1
  pythonPackageSpec:
    executorImageUri: us-docker.pkg.dev/vertex-ai/training/tf-cpu.2-8:latest
    packageUris: gs://capstone_project_f60/ct_phase_contrast/ct_phase_contrast_trainer-0.1.tar.gz
    pythonModule: trainer.task
    args:
    - --train_data_path=gs://capstone_project_f60/Train3d.csv
    - --eval_data_path=gs://capstone_project_f60/Valid3d.csv
    - --output_dir=gs://capstone_project_f60/ct_phase_contrast/trained_model_20230403_192517
    - --num_epochs=5
